# Generated by Django 4.1.3 on 2022-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email_candidato',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
