# Generated by Django 4.1.3 on 2022-11-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_candidato_email_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email_candidato',
            field=models.EmailField(max_length=254, verbose_name='Email: '),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='genero_candidato',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sexo: '),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nasc_candidato',
            field=models.DateField(verbose_name='Nascimento: '),
        ),
    ]
