# Generated by Django 4.1.3 on 2022-11-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_candidato_email_candidato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email_candidato',
            field=models.EmailField(max_length=254, verbose_name='Email: '),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nasc_candidato',
            field=models.DateField(verbose_name='Nascimento: '),
        ),
    ]
